/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "entry.pb-c.h"
void   cloudflare__zone_time_bucket__counter__init
                     (Cloudflare__ZoneTimeBucket__Counter         *message)
{
  static Cloudflare__ZoneTimeBucket__Counter init_value = CLOUDFLARE__ZONE_TIME_BUCKET__COUNTER__INIT;
  *message = init_value;
}
void   cloudflare__zone_time_bucket__init
                     (Cloudflare__ZoneTimeBucket         *message)
{
  static Cloudflare__ZoneTimeBucket init_value = CLOUDFLARE__ZONE_TIME_BUCKET__INIT;
  *message = init_value;
}
size_t cloudflare__zone_time_bucket__get_packed_size
                     (const Cloudflare__ZoneTimeBucket *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cloudflare__zone_time_bucket__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cloudflare__zone_time_bucket__pack
                     (const Cloudflare__ZoneTimeBucket *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cloudflare__zone_time_bucket__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cloudflare__zone_time_bucket__pack_to_buffer
                     (const Cloudflare__ZoneTimeBucket *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cloudflare__zone_time_bucket__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cloudflare__ZoneTimeBucket *
       cloudflare__zone_time_bucket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cloudflare__ZoneTimeBucket *)
     protobuf_c_message_unpack (&cloudflare__zone_time_bucket__descriptor,
                                allocator, len, data);
}
void   cloudflare__zone_time_bucket__free_unpacked
                     (Cloudflare__ZoneTimeBucket *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cloudflare__zone_time_bucket__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cloudflare__zone_time_bucket__counter__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket__Counter, key),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket__Counter, value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned cloudflare__zone_time_bucket__counter__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange cloudflare__zone_time_bucket__counter__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cloudflare__zone_time_bucket__counter__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "cloudflare.ZoneTimeBucket.Counter",
  "Counter",
  "Cloudflare__ZoneTimeBucket__Counter",
  "cloudflare",
  sizeof(Cloudflare__ZoneTimeBucket__Counter),
  2,
  cloudflare__zone_time_bucket__counter__field_descriptors,
  cloudflare__zone_time_bucket__counter__field_indices_by_name,
  1,  cloudflare__zone_time_bucket__counter__number_ranges,
  (ProtobufCMessageInit) cloudflare__zone_time_bucket__counter__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cloudflare__zone_time_bucket__field_descriptors[10] =
{
  {
    "map_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, map_name),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "classification",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, classification),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "doctype",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, doctype),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "pop",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, pop),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "psource",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, psource),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "result_id",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, result_id),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "db_key",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, db_key),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "db_path",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, db_path),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "kv_map_file",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, kv_map_file),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "map_entry",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, n_map_entry),
    PROTOBUF_C_OFFSETOF(Cloudflare__ZoneTimeBucket, map_entry),
    &cloudflare__zone_time_bucket__counter__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned cloudflare__zone_time_bucket__field_indices_by_name[] = {
  1,   /* field[1] = classification */
  6,   /* field[6] = db_key */
  7,   /* field[7] = db_path */
  2,   /* field[2] = doctype */
  8,   /* field[8] = kv_map_file */
  9,   /* field[9] = map_entry */
  0,   /* field[0] = map_name */
  3,   /* field[3] = pop */
  4,   /* field[4] = psource */
  5,   /* field[5] = result_id */
};
static const ProtobufCIntRange cloudflare__zone_time_bucket__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor cloudflare__zone_time_bucket__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "cloudflare.ZoneTimeBucket",
  "ZoneTimeBucket",
  "Cloudflare__ZoneTimeBucket",
  "cloudflare",
  sizeof(Cloudflare__ZoneTimeBucket),
  10,
  cloudflare__zone_time_bucket__field_descriptors,
  cloudflare__zone_time_bucket__field_indices_by_name,
  1,  cloudflare__zone_time_bucket__number_ranges,
  (ProtobufCMessageInit) cloudflare__zone_time_bucket__init,
  NULL,NULL,NULL    /* reserved[123] */
};
