/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_entry_2eproto__INCLUDED
#define PROTOBUF_C_entry_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Cloudflare__ZoneTimeBucket Cloudflare__ZoneTimeBucket;
typedef struct _Cloudflare__ZoneTimeBucket__Counter Cloudflare__ZoneTimeBucket__Counter;


/* --- enums --- */


/* --- messages --- */

struct  _Cloudflare__ZoneTimeBucket__Counter
{
  ProtobufCMessage base;
  char *key;
  int64_t value;
};
#define CLOUDFLARE__ZONE_TIME_BUCKET__COUNTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cloudflare__zone_time_bucket__counter__descriptor) \
    , NULL, 0 }


struct  _Cloudflare__ZoneTimeBucket
{
  ProtobufCMessage base;
  char *map_name;
  char *classification;
  char *doctype;
  char *pop;
  char *psource;
  char *result_id;
  char *db_key;
  char *db_path;
  char *kv_map_file;
  size_t n_map_entry;
  Cloudflare__ZoneTimeBucket__Counter **map_entry;
};
#define CLOUDFLARE__ZONE_TIME_BUCKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cloudflare__zone_time_bucket__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0,NULL }


/* Cloudflare__ZoneTimeBucket__Counter methods */
void   cloudflare__zone_time_bucket__counter__init
                     (Cloudflare__ZoneTimeBucket__Counter         *message);
/* Cloudflare__ZoneTimeBucket methods */
void   cloudflare__zone_time_bucket__init
                     (Cloudflare__ZoneTimeBucket         *message);
size_t cloudflare__zone_time_bucket__get_packed_size
                     (const Cloudflare__ZoneTimeBucket   *message);
size_t cloudflare__zone_time_bucket__pack
                     (const Cloudflare__ZoneTimeBucket   *message,
                      uint8_t             *out);
size_t cloudflare__zone_time_bucket__pack_to_buffer
                     (const Cloudflare__ZoneTimeBucket   *message,
                      ProtobufCBuffer     *buffer);
Cloudflare__ZoneTimeBucket *
       cloudflare__zone_time_bucket__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cloudflare__zone_time_bucket__free_unpacked
                     (Cloudflare__ZoneTimeBucket *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Cloudflare__ZoneTimeBucket__Counter_Closure)
                 (const Cloudflare__ZoneTimeBucket__Counter *message,
                  void *closure_data);
typedef void (*Cloudflare__ZoneTimeBucket_Closure)
                 (const Cloudflare__ZoneTimeBucket *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cloudflare__zone_time_bucket__descriptor;
extern const ProtobufCMessageDescriptor cloudflare__zone_time_bucket__counter__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_entry_2eproto__INCLUDED */
